apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: nagp-assignment
    tier: secret
type: Opaque
data:
  DB_PASSWORD: bmFncHBhc3N3b3JkMTIz
  POSTGRES_PASSWORD: bmFncHBhc3N3b3JkMTIz
  POSTGRES_USER: bmFncHVzZXI=
  POSTGRES_DB: bmFncGRi
